#!/usr/bin/env bash

UHOME=/home/myuser
BIN_PATH=$UHOME/application/current/bin/sidekiq
SHARED_PATH=$UHOME/application/shared
RVM_ENV=$UHOME/.rvm/environments/ruby-1.9.3-p448@mygemset

if [[ -s $RVM_ENV ]]
then
  source $RVM_ENV
  cd $UHOME/application/current && exec $BIN_PATH -e staging -C $SHARED_PATH/config/sidekiq.yml -P $SHARED_PATH/pids/sidekiq.pid "$@"
else
  echo "ERROR: Missing RVM environment file: '$RVM_ENV'" >&2
  exit 1
fi
