#!/usr/bin/env bash
HOME=/home/myuser
BIN_PATH=$HOME/applications/myapp/current/bin/rackup
RVM_ENV=$HOME/.rvm/environments/ruby-1.9.3-p286@mygemset

if [[ -s $RVM_ENV ]]
then
  source $RVM_ENV
  exec $BIN_PATH "$@"
else
  echo "ERROR: Missing RVM environment file: '$RVM_ENV'" >&2
  exit 1
fi
